### ISSUE TITLE
Cleanup code now that we are on 5.6

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataDoctrinePhpcrAdminBundle#447]
Are we bound to Sonta or would it be possible to increase php version to 5.6 as we did for 2.0 on CMF?

**Comment by dbu** [comment]
ups, good point. we have to coordinate with the sonata community, but i don't think that is a problem for new versions. for upcoming sonata versions, they are even going to ^7.1 but i think to work with the rest of the cmf, this release should still be ^5.6|^7.0 and then a version 3 can follow to ^7.1.

be aware that the default branch for this repo is 1.x, when you switch to master, .travis.yml is already at php 5.6, and composer at 5.5. i will fix composer.json to 5.6 as well.

**Comment by ElectricMaxxx** [comment]
I can remove all old array notations then too? Cause this was the point where i fall over the version. -------- Originalnachricht --------Betreff: Re: [sonata-project/SonataDoctrinePhpcrAdminBundle] Increase PHP version to 5.6 (#447)Von: David Buchmann An: sonata-project/SonataDoctrinePhpcrAdminBundle Cc: Maximilian Berghoff ,Author ups, good point. we have to coordinate with the sonata community, but i don't think that is a problem for new versions. for upcoming sonata versions, they are even going to ^7.1 but i think to work with the rest of the cmf, this release should still be ^5.6|^7.0 and then a version 3 can follow to ^7.1.
be aware that the default branch for this repo is 1.x, when you switch to master, .travis.yml is already at php 5.6, and composer at 5.5. i will fix composer.json to 5.6 as well.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sonata-project/SonataDoctrinePhpcrAdminBundle","title":"sonata-project/SonataDoctrinePhpcrAdminBundle","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dbu in #447: ups, good point. we have to coordinate with the sonata community, but i don't think that is a problem for new versions. for upcoming sonata versions, they are even going to ^7.1 but i think to work with the rest of the cmf, this release should still be ^5.6|^7.0 and then a version 3 can follow to ^7.1.\r\n\r\nbe aware that the default branch for this repo is 1.x, when you switch to master, .travis.yml is already at php 5.6, and composer at 5.5. i will fix composer.json to 5.6 as well."}],"action":{"name":"View Issue","url":"https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/447#issuecomment-312560737"}}}

**Comment by dbu** [comment]
oh, yes please :-) do you want to add that in the php-version branch directly?

**Comment by ElectricMaxxx** [comment]
I would do #441 proposal (Got a local WIP/POC almost ready) first and than the version stuff at least.

**Comment by dbu** [comment]
i merged #448 so composer.json is correct with what we test. i suggest to do a new branch for the code cleanup. that means in the configuration thing you can already start using short array notation.

i can also do the short array conversion separately unless you are afraid of merge conflicts.

**Comment by ElectricMaxxx** [comment]
Isn't required to do before release and a saw styleCI shouting with the new array notation. @greg0ire can we setup a local style configuration? Or do we have a centralizedone only?

**Comment by greg0ire** [comment]
Don't use the new array notation, you are going to create merge conflicts with 1.x, which is still supported, might still receive PR, and needs to be 5.3 compatible.

**Comment by ElectricMaxxx** [comment]
ähm, when fixing some stuff on 1.x i would make a PR on 1.x and merge 1.x on master afterwards, which should be easer, isn't it?

**Comment by greg0ire** [comment]
That would be exactly what you would do, yes. But if you use different notation on both branches, the merge on master step would be full of conflicts.

**Comment by greg0ire** [comment]
Unless of course you run the cs fixer with the master settings just before merging.

**Comment by dbu** [comment]
i would intend to drop active support for the 1.x branch as soon as 2.0 is released. we are hard pressed to maintain things as is. we should only do critical security fixes on 1.x and those seem at least infrequent. so i'd feel ok to move to the new array syntax here.

**Comment by greg0ire** [comment]
Ok, but when you release 2.0, consider switching to a new branching system, with deprecations and a master branch for changes. All the other Sonata packages use the deprecation system.

**Comment by ElectricMaxxx** [comment]
but asking again: this is nothing to do before release?

**Comment by greg0ire** [comment]
I do not understand your question.

**Comment by dbu** [comment]
i guess eventually somebody will do a run with php 7.1 cs fixer rules.
